# Generated by Django 4.1 on 2022-08-26 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='plae',
            new_name='place',
        ),
    ]
